jobs:
  test:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm install

      # run tests!
      - run:
          name: "Tests"
          command: echo "running tests"

  dockerize:
    machine:
      image: ubuntu-1604:201903-01
    
      working_directory: ~/repo

      steps:
        - checkout

        - run:
            name: "Logiing to dockerhub"
            command: docker login -u $USERNAME_DOCKERHUB -p $PASSWORD_DOCKERHUB
        
        - run:
            name: "Build Image"
            command: docker build -t gbo96/eventsapp:$CIRCLE_BUILD_NUM .
        
        - run:
            name: "Push docker image"
            command: docker push gbo96/eventsapp:$CIRCLE_BUILD_NUM

workflows:
  version: 2
    test_and_dockerize:
      jobs:
        - test
        - dockerize